name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rav:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/rav:latest,ignore-error=true
          cache-to: type=inline

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            for i in 1 2 3; do
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rav:latest && break || sleep 10
            done

            docker stop rav || true
            docker rm rav || true
            docker run -d \
              --name rav \
              --restart unless-stopped \
              -p 11300:11300 \
              ${{ secrets.DOCKERHUB_USERNAME }}/rav:latest
